### ISSUE TITLE
Not running in ios

### ISSUE THREAD

**Issue by krunaldodiya** [PriyaParashar93/FlutterDemo#1]
it does not start in ios

**Comment by sukhkmr19** [comment]
hi thanks for your feedback we are working on it you will get update by
this weekend Thanks.
<https://about.me/sukhbeer?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
sukhbeer kumar
about.me/sukhbeer
<https://about.me/sukhbeer?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

**Comment by krunaldodiya** [comment]
okay

**Comment by sukhkmr19** [comment]
hi,
it's now working on ios but this is just a demo project for us that include
some code only.


sukhbeer kumar
[image: https://]about.me/sukhbeer
<https://about.me/sukhbeer?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=plaintext>
